### ISSUE TITLE
Who owns the Arctos YouTube Channel?

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos-webinars#28]
We need to add our videos to the [Arctos YouTube Channel](https://www.youtube.com/channel/UCoSCkXhrjG-mwLFYRqjNyJA/videos). Who can do this?

**Comment by ebraker** [comment]
Literally doing this right now. I just created a brand channel.

**Comment by ebraker** [comment]
The vast majority of our webinars were posted to my youtube channel (based on Erika's workflow). I just now switched my channel to a [Brand channel](https://www.youtube.com/channel/UC4fY-Tsn5htubaEzTkcMQBw?view_as=subscriber) which disconnects my personal profile from the station (and is much easier than downloading all our videos and re-uploading them to Dusty's Arctos channel - where we'd also lose all of the views/comments in the process). With a brand channel, we can assign multiple managers and change ownership easily. I am loading our two most recent webinar videos (posted to Dusty's Arctos channel) so that all content is in one place, and then I will ask Michelle or Carla to redirect all of our Arctosdb.org links to the brand channel and probably have @dus delete his Arctos station (which mainly just made a playlist of my personal channel's videos).

**Comment by dustymc** [comment]
@ebraker thanks!

The arctos.database account exists for logs, and I think has just been a convenient dumping ground for other stuff. I'm happy to share the password-or-whatever, but occasionally Google gets paranoid and locks things when that happens. Something a little more organized/dedicated sounds great.

Google suggest we can't redirect through youtube, but maybe there's some place we can add a 'go here..' link so bookmarks/links don't just stop working?

**Comment by mkoo** [comment]
just emailed you about this @ebraker!
please get our videos in order under the new brand!
Once the dust settles I'll update any video links on the website that are
changed-- let me know if you want me to hang a "please excuse broken links
while we fix things" if you think it will take more than one week.
